---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install required packages
  ansible.builtin.apt:
    name: "{{ install_packages }}"
    state: present
  become: true
  tags:
    - install_packages

- name: Add the Grafana GPG key and APT repository
  ansible.builtin.shell: |
    curl https://packages.grafana.com/gpg.key | sudo apt-key add -
    add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
  args:
    warn: no
  become: true

- name: Install the grafana package
  ansible.builtin.apt:
    name: grafana
    state: present
    update_cache: yes
  notify:
    - Start grafana
    - Enable grafana
  become: true

- name: Ensure Nginx is installed
  ansible.builtin.apt:
    name: nginx
    state: present
  notify: Start and Enable Nginx
  become: true

- name: Create configure files
  ansible.builtin.template:
    src: ./templates/grafana/grafana.conf.j2
    dest: /etc/nginx/conf.d/grafana.conf
    mode: u=rw # 0600
  notify: Restart nginx
  become: true
